// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: products.sql

package db

import (
	"context"
)

const getAllProductsById = `-- name: GetAllProductsById :many
select id, product_name, brand, size, variant, country, certified_gluten_free, date_added from products where id = $1
`

func (q *Queries) GetAllProductsById(ctx context.Context, id int32) ([]Product, error) {
	rows, err := q.db.Query(ctx, getAllProductsById, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ProductName,
			&i.Brand,
			&i.Size,
			&i.Variant,
			&i.Country,
			&i.CertifiedGlutenFree,
			&i.DateAdded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
